### ISSUE TITLE
N'oubliez pas le rapport ;-) 

### ISSUE THREAD

**Issue by YannickDot** [syd26/SwissKnife33#3]
Le rapport du projet est à rendre pour demain minuit, ne l'oubliez pas svp

**Comment by YannickDot** [comment]
ça va vous gérez pour le diagramme de classes dans eclipse ?

**Comment by syd26** [comment]
Je sais pas, normalement Yvon a l'outil pour le faire.

**Comment by ygarbage** [comment]
J'essaie de m'en occuper ce soir. Je fais encore un peu de revue de code avant.
